name: Build iOS App

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up XCode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 14.0.1

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Ionic CLI
      run: npm install -g @ionic/cli

    - name: Install dependencies
      run: npm ci
      
    - name: Build Ionic Project
      run: ionic build

    - name: Add iOS platform
      run: ionic cap add ios

    - name: Sync Capacitor Configuration
      run: ionic cap sync ios

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Install iOS dependencies
      run: cd ios/App && pod install

    - name: List iOS Project Directory
      run: ls -al ios/

    - name: Build iOS App
      run: |
        cd ios
        run: xcodebuild -workspace './ios/App/App.xcworkspace' -scheme App -destination generic/platform=iOS -archivePath App.xcarchive archive

    - name: Upload release bundle
      uses: actions/upload-artifact@v3
      with:
        name: app-ios
        path: output/
        retention-days: 60
